# Generated by Django 3.2.8 on 2021-10-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='dislike',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='ex.tip'),
        ),
        migrations.AlterField(
            model_name='like',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ex.tip'),
        ),
    ]
