# Generated by Django 3.2.8 on 2021-10-26 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_auto_20211027_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
