# Generated by Django 3.2.9 on 2021-11-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
